postgres :
  image : postgres:9.4.5
  container_name : forest_meals
  ports :
    - "5446:5432"
  environment:
    - POSTGRES_DB=forest_meals
    - POSTGRES_USER=forest
    - POSTGRES_PASSWORD=secret
